### ISSUE TITLE
Not working on Anki 2.1.41beta2

### ISSUE THREAD

**Issue by AnKingMed** [Liresol/anki-custom-shortcuts#103]
The latest beta has a new error.  Damien said he doesn't expect many changes.  Happy to test as needed!  I think this may be related to the new browser changes and the rescheduling changes which likely will need a custom shortcut (unless you fixed that already in the last one)

```
Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 37, in cmd
  File "aqt/webview.py", line 136, in _onCmd
  File "aqt/webview.py", line 581, in _onBridgeCmd
  File "<decorator-gen-150>", line 2, in _linkHandler
  File "anki/hooks.py", line 89, in decorator_wrapper
  File "anki/hooks.py", line 86, in repl
  File "/Users/Nick/Library/Application Support/Anki2/addons21/zkingofstudytimers/__init__.py", line 616, in myLinkHandler
    return _old(self, url)
  File "aqt/toolbar.py", line 170, in _linkHandler
  File "aqt/toolbar.py", line 188, in _browseLinkHandler
  File "aqt/main.py", line 1069, in onBrowse
  File "aqt/__init__.py", line 101, in open
  File "aqt/browser.py", line 470, in __init__
  File "aqt/browser.py", line 532, in setupMenus
  File "aqt/hooks_gen.py", line 526, in __call__
  File "anki/hooks.py", line 34, in runHook
  File "/Users/Nick/Library/Application Support/Anki2/addons21/24411424/custom_shortcuts.py", line 283, in cs_browser_setupShortcuts
    f.actionTags.setShortcut(config_scuts["window_browser filter"])
AttributeError: 'Ui_Dialog' object has no attribute 'actionTags'
```

**Comment by Liresol** [comment]
This was indeed related to one of the browser changes, but luckily the change wasn't too bad.
I have just pushed out a patch for this, so hopefully it should be fixed.
As always, if there are any other issues, just let me know and I will look at it as soon as I can.

**Comment by AnKingMed** [comment]
Awesome. Thanks as always. I'll let you know if there are any issues. Hopefully this is the last change needed for a bit

**Comment by AnKingMed** [comment]
Did you leave a commit for this? I'm not seeing one. 

Also, is there any way you can add a new customizable shortcut for "set due date"?  This function is essentially going to replace the rememorize add-on and I'm sure people will want to use that with a controller, etc, but the current shortcut is ctrl+shift+d which isn't super convenient when doing reviews. I personally would mostly want this function in the reviewer to be customizable, but it is also in the browser now if you're being thorough

**Comment by AnKingMed** [comment]
Got another error now when going to the add screen

```
Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 36, in cmd
  File "aqt/webview.py", line 135, in _onCmd
  File "aqt/webview.py", line 580, in _onBridgeCmd
  File "<decorator-gen-144>", line 2, in _linkHandler
  File "anki/hooks.py", line 89, in decorator_wrapper
  File "anki/hooks.py", line 86, in repl
  File "/Users/Nick/Library/Application Support/Anki2/addons21/zkingofstudytimers/__init__.py", line 616, in myLinkHandler
    return _old(self, url)
  File "aqt/toolbar.py", line 169, in _linkHandler
  File "aqt/toolbar.py", line 184, in _addLinkHandler
  File "aqt/main.py", line 1064, in onAddCard
  File "aqt/__init__.py", line 101, in open
  File "<decorator-gen-14>", line 2, in __init__
  File "anki/hooks.py", line 89, in decorator_wrapper
  File "anki/hooks.py", line 80, in repl
  File "aqt/addcards.py", line 45, in __init__
  File "aqt/addcards.py", line 62, in setupChoosers
  File "aqt/modelchooser.py", line 32, in __init__
  File "<decorator-gen-36>", line 2, in setupModels
  File "anki/hooks.py", line 89, in decorator_wrapper
  File "anki/hooks.py", line 81, in repl
  File "/Users/Nick/Library/Application Support/Anki2/addons21/24411424/custom_shortcuts.py", line 252, in cs_editorChangeNoteType
    QShortcut(QKeySequence(scut), self.widget, activated=self.on_activated)
TypeError: arguments did not match any overloaded call:
  QShortcut(QWidget): argument 1 has unexpected type 'QKeySequence'
  QShortcut(Union[QKeySequence, QKeySequence.StandardKey, str, int], QWidget, member: PYQT_SLOT = 0, ambiguousMember: PYQT_SLOT = 0, context: Qt.ShortcutContext = Qt.WindowShortcut): argument 2 has unexpected type 'builtin_function_or_method'
```

**Comment by Liresol** [comment]
Thanks again for finding these, just pushed out an update for this new one too.

All of the new commits happen on the `dev` branch (which you might already know), so it should be over there.

**Comment by AnKingMed** [comment]
Awesome. Seems to be working well now. Any chance you'll be able to add a shortcut for the new Set Due Date function that has replaced Reschedule?

**Comment by Liresol** [comment]
I've added a new issue for the new shortcut (#104 ), and I think I will have time for it within the next few days.
I'm going to guess that adding the new shortcut should also fix the issue with the default, so hopefully two things can get done at once.

**Comment by Liresol** [comment]
I've just pushed out an update for the Set Due Date function (which should also fix the issue where it didn't work on the default), so hopefully things should finally be workable for the new version.

**Comment by AnKingMed** [comment]
Fantastic, thank you! I'll give it a good test run and let you know if I find any issues

**Comment by AnKingMed** [comment]
This works perfect in the browser now but it doesnt' work in the reviewer and I can't use the default shortcut in the reviewer either. Any idea what's causing that?

**Comment by Liresol** [comment]
It turns out that the reviewer shortcut is completely independent from the browser one (and looks to be completely new if I'm looking at the right function). 

I'm not sure why the default wouldn't work in the older version, but in any case, the shortcut has been added under `reviewer set due date`.

**Comment by AnKingMed** [comment]
Working really well for me now. Not sure why it wasn't before.  Thanks for the quick updates!
